#ifndef _DT_BINDINGS_GPIO_H
#define _DT_BINDINGS_GPIO_H
#define GPIO_ACTIVE_HIGH 0
#define GPIO_ACTIVE_LOW  1
#define GPIO_PUSH_PULL   0
#define GPIO_SINGLE_ENDED 2
#define GPIO_LINE_OPEN_SOURCE 4
#define GPIO_LINE_OPEN_DRAIN 6
#define GPIO_PERSISTENT 0
#define GPIO_TRANSITORY 8
#define GPIO_PULL_UP 16
#define GPIO_PULL_DOWN 32
#define GPIO_PULL_DISABLE 64
#endif
