/* EMAC (Ethernet) bring-up for the ESP32-P4 second-stage bootloader. */
#pragma once

#include <stdbool.h>

/* Clock, reset and pin-mux the Ethernet MAC so Linux's stmmac can drive it.
 *
 * NOT OPTIONAL, for the same reason p4_sdmmc_init() is not: there is no
 * ESP32-P4 clock-controller or pinctrl driver upstream, so a Linux driver
 * probes the block assuming somebody already turned it on. Touching an
 * unclocked peripheral on this part is a bus fault and the board resets on
 * the spot.
 *
 * WHY stmmac DRIVES THIS AT ALL
 *
 * The ESP32-P4's EMAC is a Synopsys DesignWare GMAC, register for register.
 * From the vendored headers:
 *
 *   0x00 MACCONFIGURATION   0x10 GMIIADDRESS   0x18 FLOWCONTROL
 *   0x04 MACFRAMEFILTER     0x14 GMIIDATA      0x1C VLANTAG
 *
 * which is dwmac1000's map exactly -- ESP-IDF's own field names give it away
 * (`emacgmiiaddr`). So mainline stmmac needs no glue file, only a device tree
 * node and the bring-up below. That is the whole reason Ethernet is cheap on
 * this board and the SD controller was not.
 *
 * WHAT THIS SETS UP
 *
 *   clock  EMAC bus clock on (SOC_CLK_CTRL1 bit 13), module reset pulsed
 *          (LP_CLKRST +0x4c bit 30), then the RMII-input clock tree:
 *          rmii/rx/tx clocks sourced from the pad, dividers at 1, and
 *          LP_CLKRST's pad_emac_txrx_clk_en selected over tx/rx.
 *   mode   PHY interface = RMII (HP_SYSTEM_GMAC_CTRL0 PHY_INTF_SEL = 4).
 *   pins   the seven RMII pads on IOMUX function 3 -- 50 CLK, 49 TX_EN,
 *          34 TXD0, 35 TXD1, 28 CRS_DV, 29 RXD0, 30 RXD1 -- plus MDC on 31
 *          and MDIO on 52 through the GPIO matrix, because those two have no
 *          EMAC IOMUX function on this part.
 *   phy    a reset pulse on GPIO 51, held low then released, so the PHY is
 *          answering MDIO by the time Linux scans the bus.
 *   mac    the station address, read out of eFuse BLOCK1 and written into
 *          MACADDRESS0. stmmac reads that register at probe and otherwise
 *          invents a random address on every boot.
 *
 * THE RMII REFERENCE CLOCK IS AN INPUT
 *
 * 50 MHz arrives on GPIO 50 from the board, which is what ESP-IDF's example
 * defaults to for this target (EXAMPLE_ETH_RMII_CLK_INPUT). Nothing here
 * configures MPLL for Ethernet, and if the board turns out to expect the SoC
 * to *generate* the reference clock instead, this is the function to change:
 * the symptom would be a PHY that answers MDIO -- MDC is driven by the MAC's
 * own bus clock -- while no frame ever moves.
 *
 * Returns true always; every step is a register write whose failure is not
 * observable here. The PHY either answers MDIO from Linux or it does not,
 * and that is the real test.
 */
bool p4_emac_init(void);

/* Scan the MDIO bus for a PHY, and say what was found.
 *
 * The one part of Ethernet this bootloader can test end to end on its own,
 * and worth testing here because Linux cannot: /dev/mem refuses peripheral
 * space (valid_phys_addr_range() rejects everything past high_memory), so
 * poking the MAC's GMIIADDRESS/GMIIDATA from userspace is not an option, and
 * stmmac's report is a single "no phy found" with no detail.
 *
 * MDC is generated by the MAC from its own bus clock, NOT from the RMII
 * reference clock, so this works independently of whether the 50 MHz pad
 * clock is right. That separation is the point: a PHY that answers here but
 * an interface that carries no frames means the data pads or the reference
 * clock; nothing answering here means MDC/MDIO muxing, the CR divider, or no
 * PHY at all.
 *
 * Sweeps every CR (MDC divider) setting, because the correct one depends on
 * SYS_CLK, whose dividers are set at runtime and not knowable statically --
 * so rather than guess, try them all and let the silicon say which works.
 * Prints one line per address that answers. */
void p4_emac_mdio_scan(void);

/* Is a 50 MHz RMII reference clock actually arriving on GPIO 50?
 *
 * The question that separates "the RMII pins are wrong" from "there is no
 * reference clock", and those two look identical from Linux: the PHY answers
 * MDIO either way (MDC comes from the MAC's own bus clock), the link comes up
 * either way (the PHY negotiates with the far end entirely on its own), and
 * the MAC's TX counter increments either way. Only the total absence of
 * received bytes gives it away, and that is equally consistent with both.
 *
 * Safe: samples the pad as a plain GPIO input before anything is muxed to the
 * EMAC, and drives nothing. If the board feeds a clock in, the samples are a
 * mix of highs and lows; if the pad is idle they are all one value, and RMII
 * input mode cannot work.
 *
 * Call BEFORE p4_emac_init(), which takes the pad over for the EMAC. */
void p4_emac_refclk_probe(void);
